// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MyButton: typeof import('./src/components/MyButton.vue')['default']
    MyComp1: typeof import('./src/components/MyComp1.vue')['default']
    MyComp2: typeof import('./src/components/MyComp2.vue')['default']
    MyComp3: typeof import('./src/components/MyComp3.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
  }
}
